FROM centos:centos7

RUN yum update -y && yum clean all
RUN yum install -y wget gcc gcc-c++ glibc-devel make ncurses-devel openssl-devel autoconf java-1.8.0-openjdk-devel git zip unzip && yum clean all
